{% set name = "gmsh" %}
{% set version = "4.2.1" %}
{% set sha256 = "1f11481e68900dc256f88aaed18d03e93b416ba01e9e8c3dc3f6d59a211f0561" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}-source.tgz
  url: http://gmsh.info/src/{{ name }}-{{ version }}-source.tgz
  sha256: {{ sha256 }}

build:
  number: 0

outputs:
  - name: gmsh
    build:
      skip: True  # [win and vc<14]
      ignore_run_exports:
        - fltk
    script: build_gmsh.sh   # [not win]
    script: bld_gmsh.bat    # [win]
    requirements:
      build:
        - cmake
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - mkl-devel  # [win]
        - {{ cdt('libselinux') }}        # [linux]
        - {{ cdt('libxcb') }}            # [linux]
        - {{ cdt('libxau') }}            # [linux]
        - {{ cdt('libxdamage') }}        # [linux]
        - {{ cdt('libxxf86vm') }}        # [linux]
        - {{ cdt('mesa-libgl-devel') }}  # [linux]
        - {{ cdt('mesa-dri-drivers') }}  # [linux]

      host:
        - gmp  # [not win]
        - openblas  # [not win]
        - occt
        - fltk
        - libpng
        - jpeg
        - libglu  # [linux]
        - mkl  # [win]
        - zlib
        - xorg-libxfixes     # [linux]
        - xorg-libxext       # [linux]
        - xorg-libxrender    # [linux]
        - xorg-libx11        # [linux]

      run:
        - gmp  # [not win]
        - openblas  # [not win]
        - mkl  # [win]
        - occt
        - libpng
        - jpeg
        - zlib
        - libglu  # [linux]
        - xorg-libxfixes     # [linux]
        - xorg-libxext       # [linux]
        - xorg-libxrender    # [linux]
        - xorg-libx11        # [linux]

    test:
      commands:
        - gmsh -help

  - name: python-gmsh
    build:
      noarch: python
    script: install_python.sh   # [not win]
    script: install_python.bat  # [win]
    requirements:
      run:
        - {{ pin_subpackage("gmsh", max_pin="x.x.x") }}
        - numpy
        - python
    test:
      imports:
        - gmsh

about:
  home: http://geuz.org/gmsh/
  license: GPL
  license_family: GPL
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE.txt'
  summary: A three-dimensional finite element mesh generator with built-in pre- and post-processing facilities
  description: |
    Gmsh is a free 3D finite element grid generator with a build-in CAD
    engine and post-processor. Its design goal is to provide a fast, light
    and user-friendly meshing tool with parametric input and advanced
    visualization capabilities. Gmsh is built around four modules:
    geometry, mesh, solver and post-processing. The specification of any
    input to these modules is done either interactively using the graphical
    user interface or in ASCII text files using Gmsh's own scripting
    language.

extra:
  recipe-maintainers:
    - guyer
    - isuruf
    - xywei
