travis:
  secure:
    BINSTAR_TOKEN: q/4dbX1LRL4ROmzJWFg4FHLy+1OBX8xjFNLEzBVyD2cGiIvxRdamBLd8xK2EPi1zIwiLRNiqhjZoMHBB33If9mOBCsKzyvzxN8FSbp5nxBv/U7cl8t3E1tncatOfhijbprvApULEfBb/qU7emWcdVHy0sv1pHtBgIXGP9r49v4VbACjcLphBH+xcLMvcbmLLdE7gFBH/JcjVgskffczwv1WOoYY6NU4GFvK02yMDSxcYVyTfDH8eloUNI3UtpN9u7WF0EOwmoz2ygPWRIe+Rx6J8bsS48i/Qp7dG0o8hUQDdSz4dI34XKbA3U4dBm5euy1FIKJjovxT71Atw+vB96n4Of0B+Zae9BgPCE9S+3f3MrpKiUrlVmqtsjBjI53PVeRIyi5OyGLzbna/THoNzJtYz0j1uLJIkxTKyR+MtHUgCgcUxYZrnHnDW3Kkv9tBlS8cq9cqiFCwKCHObBosKgP5XX36ml7sirE2/rs95uKpycP6YvbjtLwpwUzOUT4Z07ln2cNNEa43rdTmX5Gg++dlO+tXii4RJuELFDrOX3mgLZnzlkatXzoTwpxcfTCtzSF+E98YVS+lQnyubyppL7UvGVqt3cpdqiCyJ7bKj8AOjo3sDHIZrIXPJqb1NTh1M9jaYrxQoD/5wZ264kkSe9vY5F3L5tQn9EXyVyRSLjIc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
